use_frameworks!

target 'HOBProgressHUD_Example', :exclusive => true do
  pod 'HOBProgressHUD', :path => '../'
end

target 'HOBProgressHUD_Tests', :exclusive => true do
  pod 'HOBProgressHUD', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
